-- FINAL SQL FIX: Run this to ensure ALL tables have the correct columns

-- PRODUCTS
ALTER TABLE products ADD COLUMN IF NOT EXISTS instock BOOLEAN DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS purchaseurl TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS pdffile TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS status TEXT;

-- ORDERS
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total NUMERIC;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS totalprice NUMERIC;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS items JSONB;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS createdat TIMESTAMPTZ DEFAULT NOW();

-- DONATIONS
ALTER TABLE donations ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS donor_name TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS recipient TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS amount NUMERIC;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS program TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Success';
ALTER TABLE donations ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS description TEXT;
